name: "All post-commit tests"

on:
  workflow_call:
    inputs:
      build-type:
        required: false
        default: Release
        type: string
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        default: Release
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - ASan
          - TSan
      with-retries:
        default: false
        type: boolean
        description: "Re-run failed jobs (max 3)"
  push:
    branches: ["main"]

permissions:
  actions: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write
  packages: write
  checks: write

run-name: All post-commit tests${{ (github.event_name == 'workflow_dispatch' && inputs.with-retries) && ' (with retries)' || ''}}

jobs:
  dummy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run dummy test
        run: |
          echo "Running dummy test..."
          echo "Test status: PASS"
          exit 0
